#spring.application.name=eCommerce
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dipak_e_commerce
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  logging:
    level:
      org:
        hibernate: TRACE

