# Application Name
spring:
  application:
    name: eCommerce

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/dipak_e_commerce
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

# Hibernate Logging Configuration
logging:
  level:
    org:
      hibernate: TRACE

# Custom API prefix configuration
api:
  prefix: /api/v1
