## Application Name
#spring:
#  application:
#    name: eCommerce
#
#  # Database Configuration
#  datasource:
#    url: jdbc:postgresql://localhost:5432/dipak_e_commerce
#    username: postgres
#    password: root
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        flushMode: COMMIT
#        format_sql: true
#        use_sql_comments: true
#        type:
#          descriptor.sql.BasicBinder: TRACE  # Enable bound parameters logging
#
## Hibernate Logging Configuration
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type.descriptor.sql: TRACE  # Log the binding of parameters
#    com.dipakraut.eCommerce: DEBUG  # Log application-specific debug messages
#    #org.springframework: DEBUG        # Log Spring framework messages
#
## Custom API prefix configuration
#api:
#  prefix: /api/v1
